{
 "title": "Pagerduty Scorecard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mttaMttrServiceNames",
    "query": {
     "query": "label_values(compliantServiceName)"
    }
   },
   { "name": "teamName", "query": { "query": "label_values(allTeamNames)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Compliancy Master List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pagerduty_service_names_metric" }
   ]
  },
  {
   "title": "Search For Compliancy By Team Name",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pagerduty_service_names_metric{allTeamNames=\"${teamName}\"}"
    }
   ]
  },
  {
   "title": "MTTA/MTTR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pagerduty_mtta_analytics_metric{compliantServiceName=\"${mttaMttrServiceNames}\"}"
    },
    {
     "expr": "pagerduty_mttr_analytics_metric{compliantServiceName=\"${mttaMttrServiceNames}\"}"
    }
   ]
  },
  {
   "title": "MTTA/MTTR",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pagerduty_mtta_analytics_metric "
    },
    {
     "expr": "(pagerduty_mttr_analytics_metric - pagerduty_mtta_analytics_metric) + pagerduty_mtta_analytics_metric"
    }
   ]
  },
  {
   "title": "Total Services",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pagerduty_total_services_metric"
    }
   ]
  },
  {
   "title": "Compliant Services",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pagerduty_total_services_compliant_metric"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pagerduty_total_users_metric" }
   ]
  },
  {
   "title": "Total Business Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "pagerduty_total_business_services_metric"
    }
   ]
  },
  {
   "title": "Total Teams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "pagerduty_total_teams_metric" }
   ]
  }
 ]
}